[tool.poetry]
name = "vanguard"
version = "0.2.0"
description = ""
authors = ["Chris Larabee"]

[tool.poetry.dependencies]
python = "^3.8.5"
SQLAlchemy = "^1.3.22"
kafka-python = "^2.0.2"
pandas = "^1.1.5"
