version: '3.1'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
     - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    ports:
     - "9092:9092"
    expose:
     - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "incoming_calls:1:1"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
  # vanguard:
  #   image: tensorflow/serving
  #   tty: true
  #   model_name: cenblocks
  #   model_base_path: ./vanguard/models/cenblocks
  #   ports:
  #     - "8500:8500"
  #   rest_api_ports:
  #     - "8501:8501"
  #   volumes:
  #     - ./components/vanguard:/vanguard
  #     - ./components/db:/vanguard/db
  #     - ./datastore/sim_db:/datastore/sim_db
  callcenter:
    build: ./components/callcenter/
    tty: true
    ports:
    - "8001:8001"
    volumes:
      - ./components/callcenter:/components/callcenter
      - ./components/db:/components/db
      - ./datastore/sim_db:/datastore/sim_db