[tool.poetry]
name = "vanguard"
version = "0.2.0"
description = ""
authors = ["Chris Larabee"]

[tool.poetry.dependencies]
python = "3.8.5"
SQLAlchemy = "^1.3.22"
kafka-python = "^2.0.2"
tfx = "^0.25.0"
tensorflow = "^2.3.1"

[tool.poetry.dev-dependencies]
flake8-black = "^0.2.1"
pytest = "^6.2.2"
